In [16]:
import numpy as np

f = open("instances/aaa1", "r")
content = f.read()
f.close()
#print(content)

lines = content.split("\n")

array = []

for line in lines:
    if line.startswith('#'): # filter lines of comment
        pass
    else :
        numbers = line.split(" ") 
        while numbers.count('') >0:
            numbers.remove('')
        for j in range(len(numbers)):
            numbers[j] = int(numbers[j])

        if numbers != []:
            array.append(numbers)

print(array)

nb_jobs = array[0][0] #number of jobs
nb_machines = array[0][1] #number of machines

print(nb_jobs)
print(nb_machines)

[[2, 3], [0, 3, 1, 3, 2, 2], [1, 2, 0, 2, 2, 4]]
2
3


In [17]:
machines = np.matrix(array[1:])[:,::2]
print(machines)

[[0 1 2]
 [1 0 2]]


In [18]:
durations = np.matrix(array[1:])[:,1::2]
print(durations)

[[3 3 2]
 [2 2 4]]


In [19]:
naive_makespan = np.sum(durations)

In [26]:
list_r = []
for i in range(nb_machines):
    list_r.append("r"+str(i+1))

list_r

['r1', 'r2', 'r3']

In [174]:
from numpy.random import default_rng

list_solution = []

for i in range(nb_machines):
    rng = default_rng()
    list_ressource = rng.choice((1,nb_jobs), size=nb_jobs, replace=False).tolist()
    list_solution.append(list_ressource)
    
list_solution

[[1, 2], [1, 2], [1, 2]]

In [198]:
list_tuples = []
l = []

for i in range(len(list_solution)):
    for j in range(nb_jobs):
        job_number = list_solution[i][j]
        operation = machines[job_number-1,i]+1
#         print(job_number, operation)
        t = (job_number, operation)
        list_tuples.append(t)
        
list_tuples

[(1, 1), (2, 2), (1, 2), (2, 1), (1, 3), (2, 3)]

In [201]:

l = []

for i in range(len(list_solution)):
    list_tuples = []
    for j in range(nb_jobs):
        job_number = list_solution[i][j]
        operation = machines[job_number-1,i]+1
#         print(job_number, operation)
        t = (job_number, operation)
        list_tuples.append(t)
    l.append(list_tuples)

l

[[(1, 1), (2, 2)], [(1, 2), (2, 1)], [(1, 3), (2, 3)]]

In [191]:
machines[0,0]

0

In [175]:
len(list_solution)

3

In [207]:
import pandas as pd
df = pd.DataFrame(l, index=list_r)
df

0       1
r1  (1, 1)  (2, 2)
r2  (1, 2)  (2, 1)
r3  (1, 3)  (2, 3)